apiVersion: v1
kind: Secret
metadata:
  name: secretsosmed
  namespace: staging
type: Opaque
data:
  DB_USER: bWFjcm9zcw==
  DB_PASS: MTIzNDU2Nzg5
  DB_NAME: ZGJzb3NtZWQ=
  DB_HOST: ZGJtYWNyb3NzLmNkY29mcHp3bWRpYi51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
